(function(g){var window=this;var R1=function(a){a.isActive()||a.start()},S1=function(a){var b={languageCode:a.languageCode,
languageName:a.languageName,displayName:g.RG(a),kind:a.kind,name:a.name,id:a.id,is_servable:a.i,is_default:a.isDefault,is_translateable:a.isTranslateable,vss_id:a.vssId};a.translationLanguage&&(b.translationLanguage=a.translationLanguage);return b},T1=function(a){return a.translationLanguage?a.translationLanguage.languageCode:a.languageCode},RFa=function(a,b){var c=new g.QG;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.i=a.i;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},SFa=function(){this.l=[];
this.i=[]},U1=function(a,b){return b?a.i.concat(a.l):a.i},V1=function(a,b){switch(b.kind){case "asr":TFa(b,a.l);
break;default:TFa(b,a.i)}},TFa=function(a,b){g.cb(b,function(c){return c?a.toString()===c.toString():!1})||b.push(a)},W1=function(){g.E.call(this);
this.l=new SFa;this.C=[]},X1=function(a,b,c){W1.call(this,a);
this.audioTrack=c;this.i=null;this.C=b.QA},Y1=function(){this.segments=[]},UFa=function(a,b){var c=g.vb(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.jb(a.segments,c),g.jb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.rb(a.segments,c,0,b),g.rb(a.segments,c+1,0,b)))},Z1=function(a,b,c,d,e,f){g.E.call(this);
this.policy=a;this.player=b;this.X=c;this.I=d;this.C=e;this.L=f;this.W=this.player.T();this.B=new Y1;this.l=this.u=this.i=null;this.J=new g.J(this.DE,1E3,this);this.events=new g.$M(this);g.I(this,this.J);g.I(this,this.events);this.events.N(b,"SEEK_COMPLETE",this.qB);this.qB();this.DE()},VFa=function(a,b){var c=g.ly(g.By(b,a.policy,{})),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.l=g.zt(c,d,3,100).then(function(e){a:{a.na();if(a.u){var f=!(a.C?e.response:e.responseText)||400<=e.status,h=g.ZA(e);if(h){e=g.By(a.u,a.policy,{});f=a.u;g.sy(f.l,e,h);f.requestId=e.get("req_id");VFa(a,a.u);break a}f||null==a.I||(h=a.u.i[0],a.C?a.I(e.response,1E3*(h.startTime+a.player.pc())):a.I(e.responseText,1E3*(h.startTime+a.player.pc())))}a.u=null;a.l=null}});
a.u=b;UFa(a.B,a.u.i[0].va)},$1=function(a,b){W1.call(this,b.T());
this.i=a;this.G=b;this.u=null;this.B=!1;this.I=g.uG(this.G.T())&&!this.i.isManifestless},WFa=function(a,b){var c=[],d;
for(d in a.i.i)if(a.i.i.hasOwnProperty(d)){var e=a.i.i[d];if(g.iN(e,b||null)){var f="en",h="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind;c.push(new g.QG({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},XFa=function(a,b){return null!=b&&b in a.i.i?a.i.i[b]:null},YFa=function(a,b,c){var d=[],e;
for(e in a.i.i)if(a.i.i.hasOwnProperty(e)){var f=a.i.i[e];if(g.iN(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},a2=function(a,b,c,d,e){W1.call(this,e||null);
this.videoId=b;this.cE=d;this.B={};this.i=null;b=c||g.xp(a).hl||"";b=b.split("_").join("-");this.u=g.zp(a,{hl:b})},b2=function(a){if(!ZFa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace($Fa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},c2=function(a,b,c,d,e,f){var h={};
g.Sa(h,b);g.Sa(h,a.params);g.Sa(h,c);var l={};g.Sa(l,b.Ic);a.params.Ic&&g.Sa(l,a.params.Ic);g.Sa(l,c.Ic);h.Ic=l;g.X.call(this,{D:"div",K:"caption-window",U:{id:"caption-window-"+a.id,dir:1===h.Ve?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:h.lang},S:[{D:"span",K:"captions-text",U:{style:"word-wrap: normal; display: block;"}}]});this.C=[];this.ca=!1;this.l=a;this.ia=this.ea=null;this.playerWidth=e;this.playerHeight=f;this.I=null;this.maxWidth=.96*e;this.za=.96*f;this.i=h;this.qb=c;this.B=
this.ha("captions-text");this.Va=""!==this.B.style.getPropertyValue("box-decoration-break")||""!==this.B.style.getPropertyValue("-webkit-box-decoration-break");this.ga=d/360*16;this.type=0;this.Da=this.ga*aGa(l);a=new g.Wt(this.element,!0);g.I(this,a);a.subscribe("dragstart",this.sJ,this);a.subscribe("dragmove",this.rJ,this);a.subscribe("dragend",this.qJ,this);this.La=this.Ha=0;b="";this.i.windowOpacity&&(a=b2(this.i.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.i.windowOpacity+")");a={"background-color":b,
display:!1===this.i.isVisible?"none":"","text-align":bGa[this.i.textAlign]};this.Va&&(a["border-radius"]=b?this.Da/8+"px":"");if(this.u=2===this.l.params.Ve||3===this.l.params.Ve)b=this.element,c="vertical-rl",1===this.i.pA&&(c="vertical-lr"),g.Be&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.hg(b,"-o-writing-mode",c),g.hg(b,"-webkit-writing-mode",c),g.hg(b,"writing-mode",c),g.hg(b,"text-orientation","upright"),g.N(b,"ytp-vertical-caption"),3===this.l.params.Ve&&(g.hg(b,"text-orientation",""),g.hg(b,"transform",
"rotate(180deg)"));g.hg(this.element,a);switch(this.i.Oh){case 0:case 1:case 2:g.N(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.N(this.element,"ytp-caption-window-bottom")}},aGa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},cGa=function(a,b){var c={},d=b.background?b.background:a.i.Ic.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.i.Ic.backgroundOpacity;d=b2(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Va&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Da/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.ga*aGa(b)+"px";d=1;e=b.color||a.i.Ic.color;if(b.color||null!=b.textOpacity)e=b2(e),d=null==b.textOpacity?a.i.Ic.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.kx&&(h=e=b.kx);var l=a.ga/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=r;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.Yp()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.i.Ic.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.bi&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.OL&&(c.visibility="hidden");1===b.YD&&a.u&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.zG||g.bs,3===a.l.params.Ve?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Ai||2===b.Ai||3===b.Ai||4===b.Ai||5===b.Ai)if(g.zG)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Ai){case 4:case 3:c["text-emphasis-position"]="under left";
c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},dGa=function(a){a.I=g.Ie("SPAN");
g.hg(a.I,{display:"block"});g.N(a.I,"caption-visual-line");a.B.appendChild(a.I)},eGa=function(a,b){var c=g.Ie("SPAN");
g.hg(c,{display:"inline-block","white-space":"pre-wrap"});g.hg(c,cGa(a,b));c.classList.add("ytp-caption-segment");a.I.appendChild(c);c.previousElementSibling&&(g.hg(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.hg(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},fGa=function(a,b,c){a.ca=a.ca||!!c;
var d={};g.Sa(d,a.i.Ic);g.Sa(d,c||b.i);g.Sa(d,a.qb.Ic);(c=!a.I)&&dGa(a);for(var e=a.ea&&a.ia&&g.Ub(d,a.ia)?a.ea:eGa(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(dGa(a),e=eGa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Je(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.zG||!g.lg(n.children[2],"text-emphasis")||(m=a.u?"padding-right":"padding-top",g.lg(n.children[2],"text-emphasis-position")&&(m=a.u?"padding-left":"padding-bottom"),
g.De?g.hg(e,m,"1em"):g.hg(e,m,"0.5em")))}a.ia=d;a.ea=e;a.C.push(b)},d2=function(a,b,c,d,e,f,h){c2.call(this,a,b,c,d,e,f,h);
this.type=1},e2=function(a,b,c,d,e,f,h){c2.call(this,a,b,c,d,e,f,h);
this.type=2;this.J=[];this.X=this.L=this.la=0;this.Y=NaN;this.Oa=0;this.Ya=null;this.ma=new g.J(this.NO,433,this);g.N(this.element,"ytp-caption-window-rollup");g.I(this,this.ma);g.hg(this.element,"overflow","hidden")},gGa=function(a,b){if(!b)return"";
a.u&&1!==a.l.params.pA&&(b*=-1);return"translate"+(a.u?"X":"Y")+"("+b+"px)"},hGa=function(a){a.J=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.l.params.tk,c=0,d=0,e=a.J.length-1;c<b&&-1<e;){var f=a.J[e];d+=a.u?f.offsetWidth:f.offsetHeight;c++;e--}a.J.length<b&&(d*=b/a.J.length);a.L=d;b=Math;c=b.max;isNaN(a.Y)&&((d=a.i.Uk)?(e=g.Ie("SPAN"),g.Qe(e,"\u2013".repeat(d)),g.hg(e,cGa(a,a.i.Ic)),a.B.appendChild(e),a.Y=e.offsetWidth,a.B.removeChild(e)):a.Y=0);d=a.B;a.X=c.call(b,a.Y,a.Oa,(a.u?d.offsetHeight:d.offsetWidth)+1)},iGa=function(a,b){hGa(a);
var c=a.J.reduce(function(e,f){return(a.u?f.offsetWidth:f.offsetHeight)+e},0);
c=a.L-c;if(c!==a.la){var d=0<c&&0===a.la;b||isNaN(c)||d||(g.N(a.element,"ytp-rollup-mode"),g.$m(a.ma));g.hg(a.B,"transform",gGa(a,c));a.la=c}hGa(a)},f2=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.yD.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.i=h},g2=function(a,b,c,d,e){g.yD.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.i=[]},jGa=function(a){var b="_"+h2++;
return new g2(0,0x8000000000000,0,b,a)},lGa=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.Cd){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=kGa(l.textContent,n.textContent,p.textContent,f.textContent,h);return new f2(a,b,e,c,l,d,m)}switch(m.Cd){case 9:case 10:m.Ai=1;break;case 11:m.Ai=2;break;case 12:m.Ai=3;break;case 13:m.Ai=4;break;case 14:m.Ai=5}return new f2(a,b,e,c,l.textContent||"",d,m)},kGa=function(a,b,c,d,e){var f=g.Yp(),h=
f?g.Ie("DIV"):g.Ie("RUBY"),l=g.Ie("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.Ie("DIV"):g.Ie("RP");a.textContent=b;h.appendChild(a);b=f?g.Ie("DIV"):g.Ie("RT");b.textContent=c;h.appendChild(b);c=e.Cd;if(10===c||11===c||12===c||13===c||14===c)if(g.hg(b,"text-emphasis-style","filled circle"),g.hg(b,"text-emphasis-color","currentcolor"),g.hg(b,"webkit-text-emphasis","filled circle"),11===e.Cd||13===e.Cd)g.hg(b,"webkit-text-emphasis-position","under left"),g.hg(b,"text-emphasis-position","under left");c=!0;if(4===e.Cd||7===e.Cd||12===e.Cd||
14===e.Cd)g.hg(h,"ruby-position","over"),g.hg(h,"-webkit-ruby-position","before");else if(5===e.Cd||6===e.Cd||11===e.Cd||13===e.Cd)g.hg(h,"ruby-position","under"),g.hg(h,"-webkit-ruby-position","after"),c=!1;e=f?g.Ie("DIV"):g.Ie("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.hg(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.hg(f,"display","none"),f=f.nextElementSibling,g.hg(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.hg(h.lastElementChild,"display","none"),d?(g.hg(h,"padding-top","0.6em"),g.hg(f,"top","0")):(g.hg(h,"padding-bottom","0.6em"),g.hg(f,"bottom","0")));return h},i2=function(){g.E.apply(this,arguments)},j2=function(a){i2.call(this);
this.C=a;this.B={};this.W={};this.X={};this.I="_"+h2++;this.L={};this.u=this.i=null;this.J=!0},k2=function(a,b){var c=a.getAttribute(b);
if(null!=c)return Number(c)},l2=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"===c},m2=function(a,b){var c=k2(a,b);
return void 0!==c?c:null},o2=function(a,b){var c=a.getAttribute(b);
if(null!=c)return n2.test(c),c},mGa=function(a,b){var c={},d=b.getAttribute("ws");
g.Sa(c,d?a.X[d]:a.C);d=m2(b,"mh");null!=d&&(c.Wo=d);d=m2(b,"ju");null!=d&&(c.textAlign=d);d=m2(b,"pd");null!=d&&(c.Ve=d);d=m2(b,"sd");null!=d&&(c.pA=d);d=o2(b,"wfc");null!=d&&(c.windowColor=d);d=k2(b,"wfo");void 0!==d&&(c.windowOpacity=d/255);return c},nGa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Sa(c,a.W[d]);d=m2(b,"ap");null!=d&&(c.Oh=d);d=k2(b,"cc");null!=d&&(c.Uk=d);d=k2(b,"ah");null!=d&&(c.Pg=d);d=k2(b,"rc");null!=d&&(c.tk=d);d=k2(b,"av");null!=d&&(c.Ci=d);return c},oGa=function(a,b,c,d){var e={};
g.Sa(e,nGa(a,b));g.Sa(e,mGa(a,b));d?g.Ub(e,a.C)?(d=a.I,e=a.C):d="_"+h2++:d=b.getAttribute("id")||"_"+h2++;a=k2(b,"t")+c;b=k2(b,"d")||0x8000000000000;if(2===e.Ve||3===e.Ve)c=e.tk,e.tk=e.Uk,e.Uk=c;return new g2(a,b,0,d,e)},p2=function(a){i2.call(this);
this.I=a;this.i=new Map;this.B=new Map;this.C=new Map;this.u=new Map},q2=function(a){a=g.ee(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},pGa=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.B.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.C.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.tk=a);b=b.ccColCount;void 0!==b&&(f.Uk=b);if(2===f.Ve||3===f.Ve)b=f.tk,f.tk=f.Uk,f.Uk=b;return new g2(c,d,0,e,f)},s2=function(){this.u=this.time=this.mode=this.l=0;
this.B=new r2(this);this.C=new r2(this);this.i=[];this.clear()},rGa=function(a,b,c){if(255===a&&255===b||!a&&!b)return{Im:a,
Qk:b,result:0};a=qGa[a];b=qGa[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.Qk===d;if(d)return{Im:a,Qk:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Im:a,Qk:b,result:2};return{Im:a,Qk:b,result:3}},tGa=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.u&&a.reset(),a.B.l.clear(),a.C.l.clear()):(a.u=0,sGa(a.B,b,c,d))},uGa=function(a,b){a.i.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.q(a.i),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?tGa(a,d.GC,d.HC,b):1===d.type&&a.l&496&&sGa(a.C,d.GC,d.HC,b);a.i.length=0},t2=function(){this.type=0},u2=function(){this.state=this.Qk=this.Im=0},vGa=function(){this.timestamp=this.i=0},v2=function(a){this.C=a;
this.u=[];this.i=this.l=this.row=0;this.style=new t2;for(a=this.B=0;15>=a;a++){this.u[a]=[];for(var b=0;32>=b;b++)this.u[a][b]=new vGa}},w2=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.C.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var r=a.u[m][p];
if(0!==r.i){0===c&&(c=m,d=p);n=String.fromCharCode(r.i);var t=r.timestamp;t<e&&(e=t);r.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===r.i||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.C.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.u[h][m],r=p.i,0!==r&&(0===c&&(c=h,d=m),n=String.fromCharCode(r),t=p.timestamp,t<=e&&(e=t),l+=n,p.reset()),32===m||0===r)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},AGa=function(a,b){switch(a){case 0:return wGa[(b&127)-32];
case 1:return xGa[b&15];case 2:return yGa[b&31];case 3:return zGa[b&31]}return 0},x2=function(a){return a.u[a.row][a.l]},y2=function(a,b,c){2<=b&&1<a.l&&(--a.l,x2(a).i=0);
var d=x2(a);d.timestamp=a.C.time+0;d.i=AGa(b,c);32>a.l&&a.l++},BGa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.u[b+e][f],l=a.u[c+e][f];
h.i=l.i;h.timestamp=l.timestamp}},z2=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.u[b+d][e].reset()},A2=function(a){a.row=0<a.i?a.i:1;
a.l=1;z2(a,0,15)},B2=function(a){this.u=a;
this.C=0;this.style=new t2;this.I=new v2(this.u);this.J=new v2(this.u);this.text=new v2(this.u);this.l=this.I;this.B=this.J;this.i=this.l},C2=function(a,b,c){var d=a.l,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.i||(w2(d,c),A2(a.l),A2(a.B),d.row=15,d.i=b,e=!0)}a.style.set(3);a.i=d;a.i.style=a.style;a.u.mode=1<<d.B;e?d.l=1:d.i!==b&&(d.i>b?(w2(d,c),z2(d,d.row-d.i,b)):d.row<b&&(b=d.i),d.i=b)},CGa=function(a){a.style.set(1);
a.i=a.B;a.i.i=0;a.i.style=a.style;a.u.mode=1<<a.i.B},DGa=function(a){a.style.set(4);
a.i=a.text;a.i.style=a.style;a.u.mode=1<<a.i.B},r2=function(a){this.i=a;
this.C=0;this.u=new B2(this.i);this.I=new B2(this.i);this.l=new u2;this.B=this.u},sGa=function(a,b,c,d){a.l.update();
b=rGa(b,c,a.l);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Im;c=b.Qk;if(32<=e||!e)a.i.mode&a.i.l&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.B.i,b&96&&y2(a,0,b),c&96&&y2(a,0,c),0!==b&&0!==c&&3===a.style.type&&w2(a,d));else if(e&16)a:if(!a.l.matches(e,c)&&(b=a.l,b.Im=e,b.Qk=c,b.state=2,b=e&8?a.I:a.u,a.B=b,a.i.mode=1<<(a.C<<2)+(b.C<<1)+(4===b.style.type?1:0),(a.i.mode|1<<(a.C<<2)+(b.C<<1)+(4!==b.style.type?1:0))&a.i.l))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.i;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.i&&(d=c.i,d===c.row))break;var f=1+c.row-c.i,h=1+d-c.i;BGa(c,h,f,c.i);b=f;e=c.i;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));z2(c,b,e)}}c.row=d;c.l=a+1}else switch(e&7){case 1:switch(c&112){case 32:y2(b.i,0,32);break a;case 48:57===c?(d=b.i,x2(d).i=0,32>d.l&&d.l++):y2(b.i,1,c&15)}break;case 2:c&32&&y2(b.i,2,c&31);break;case 3:c&32&&y2(b.i,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:CGa(b);
break;case 33:d=b.i;1<d.l&&(--d.l,x2(d).i=0);break;case 36:d=b.i;b=x2(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.u[a][c]===b){for(;32>=c;c++)d.u[a][c].reset();break}break;case 37:C2(b,2,d);break;case 38:C2(b,3,d);break;case 39:C2(b,4,d);break;case 40:y2(b.i,0,32);break;case 41:b.style.set(2);b.i=b.l;b.i.i=0;b.i.style=b.style;b.u.mode=1<<b.i.B;break;case 42:d=b.text;d.i=15;d.style.set(4);A2(d);DGa(b);break;case 43:DGa(b);break;case 44:a=b.l;switch(b.style.get()){case 1:case 2:case 3:w2(a,d)}z2(a,
0,15);break;case 45:b:{a=b.i;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.l=1;break b}case 3:}2>a.i&&(a.i=2,a.row<a.i&&(a.row=a.i));b=a.row-a.i+1;w2(a,d);BGa(a,b,b+1,a.i-1);z2(a,a.row,1)}break;case 46:z2(b.B,0,15);break;case 47:w2(b.l,d),b.B.updateTime(b.u.time+0),d=b.B,b.B=b.l,b.l=d,CGa(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.i,32<(d.l+=c&3)&&(d.l=32)}}},EGa=function(){},D2=function(a,b,c){this.J=a;
this.I=c;this.version=this.C=this.u=this.byteOffset=0;this.i=new DataView(this.J);this.l=[]},E2=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.i.getUint8(b)},F2=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.i.getUint32(b)},G2=function(a,b){i2.call(this);
this.u=a;this.B=b;this.track="CC3"===this.B.languageName?4:0;this.i=new s2;this.i.l=1<<this.track},H2=function(a){if("string"===typeof a)return!1;
a=new D2(a,8,0);return FGa(a)},FGa=function(a){if(!(a.byteOffset<a.i.byteLength)||1380139777!==F2(a))return!1;
a.version=E2(a);if(1<a.version)return!1;E2(a);E2(a);E2(a);return!0},I2=function(){i2.call(this)},GGa=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.bi=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new f2(b,c,d,e.id,p.nodeValue,f||0<n,g.Pb(l)?void 0:l),m.push(p),e.i.push(p);else{var r={};g.Sa(r,l);GGa(a,b,c,d,e,!0,p,r,m)}}},J2=function(a){var b=a.split(":");
a=0;b=g.q(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},HGa=function(a,b,c,d){d=Object.assign({Wo:0},d);
return new g2(a,b,c,"_"+h2++,d)},K2=function(a){g.E.call(this);
this.l=a;this.i=null},JGa=function(a){var b={};
if(a=T1(a))b.lang=a,IGa.test(a)&&(b.Ve=1);return b},N2=function(a){g.hN.call(this,a);
var b=this;this.G=a;this.i=this.G.T();this.videoData=this.G.getVideoData();this.Va=this.G.Ka();this.B={Ic:{}};this.C={Ic:{}};this.Y=[];this.W={};this.ma={};this.X=!1;this.La=g.ooa(this.videoData,this.G);this.Ya=!!this.videoData.captionTracks.length;this.qb=!!this.videoData.fh;this.Ha="3"===this.i.controlsType;this.u=this.J=this.L=this.la=this.Ja=null;this.za=new K2(this.i);this.l=null;this.ia=new g.$M(this);this.Da=new g.X({D:"div",K:"ytp-caption-window-container",U:{id:"ytp-caption-window-container"}});
var c=null,d=g.Pn("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.zn(d));this.storage=c;c=a.dd();d=!(!c||!c.qs());this.Oa=!(!c||!c.rs());this.I=this.Ha&&d&&!this.La;this.ea=!this.I&&this.Ha&&this.Oa&&this.La;g.I(this,this.za);this.I?this.ga=this.ca=null:(this.ca=new g.Xm(this.GA,void 0,this),g.I(this,this.ca),this.ga=new g.J(this.dQ,2E3,this),g.I(this,this.ga));g.I(this,this.ia);this.i.Z("caption_window_container_killswitch")||g.XM(this.player,this.Da.element,4);g.I(this,this.Da);this.I||
this.ia.N(a,"resize",this.IA);this.ia.N(a,"onPlaybackAudioChange",this.WM);this.ia.N(a,g.BD("captions"),function(e){b.Bd(e)});
this.ia.N(a,g.CD("captions"),function(e){b.rf(e)});
L2(this,M2(this,"display-settings")||{})},KGa=function(a){if(1===a.i.ma||1===a.videoData.ro||"alwayson"===g.cI(a.videoData,"yt:cc"))return!0;
if(2===a.i.ma){var b;g.yG(a.i)?b=(0,g.NDa)():b=M2(a,"module-enabled");if(null!=b)return!!b}if(a.videoData.captionTracks.length)var c=a.player.getAudioTrack().u;b=a.player.getAudioTrack().captionsInitialState;var d=g.cI(a.videoData,"yt:cc");if(void 0===O2(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===b)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===b)return"on"===d}else return"on"===d;return"ON"===c||"on"===g.cI(a.videoData,"yt:cc")},P2=function(a,b){if(a.l&&(void 0===b||!b)||
!a.videoData.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.l||"FORCED_ON"===c.u},O2=function(a){var b=void 0,c=g.Qq(g.Oq.getInstance(),65);
g.yG(a.i)&&null!=c&&(b=!c);return b},R2=function(a,b){if(a.u){if(a.J&&a.J.C)return a.J.C;
var c=b;c||(c=a.qb?!1:a.Ya?!1:!0);c=U1(a.u.l,c);for(var d=[a.videoData.captionsLanguagePreference,a.i.captionsLanguagePreference,g.cI(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(T1(c[f])===d[e])return c[f];return a.J&&a.J.B?a.J.B:(d=c.find(function(h){return h.isDefault}))?d:c[0]||Q2(a)}return null},Q2=function(a){return a.J&&a.J.l},S2=function(a){var b=Q2(a);
return!!b&&a.l===b},LGa=function(a,b){for(var c=a.G.dd().he().textTracks,d=a.l.toString(),e=0;e<c.length;e++){var f=c[e];
f.id===d&&(b?"showing"!==f.mode&&(f.mode="showing"):"showing"===f.mode&&(f.mode="disabled"))}},U2=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.X=c,a.X&&(g.yG(a.i)?(0,g.$_)(!!b):T2(a,"module-enabled",!!b)));a.l=b;P2(a)&&(a.l=Q2(a));a.load()},MGa=function(a,b){a.i.Z("caption_window_container_killswitch")?g.XM(a.player,b,4):a.Da.element.appendChild(b)},NGa=function(a,b){var c=a.Va.getVideoContentRect(!0).height;
if(!c)return null;var d=a.l?a.l.languageCode:null;!b.params.Ve&&d&&IGa.test(d)&&(b.params.Ve=1);d=a.Va.getPlayerSize();switch(null!=b.params.Wo?b.params.Wo:1<b.i.length?1:0){case 1:return new d2(b,a.B,a.C,c,d.width,d.height,a.i.experiments);case 2:return new e2(b,a.B,a.C,c,d.width,d.height,a.i.experiments);default:return new c2(b,a.B,a.C,c,d.width,d.height,a.i.experiments)}},L2=function(a,b,c){c=void 0===c?!1:c;
var d=V2.Ic;a.B={};g.Sa(a.B,V2);a.B.Ic={};g.Sa(a.B.Ic,d);a.C={Ic:{}};var e=b.backgroundOverride?a.C:a.B,f=b.background||d.background;n2.test(f);e.Ic.background=f;e=b.colorOverride?a.C:a.B;f=b.color||d.color;n2.test(f);e.Ic.color=f;e=b.windowColorOverride?a.C:a.B;f=b.windowColor||V2.windowColor;n2.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.C:a.B;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Ic.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.C:a.B;f=b.fontSizeIncrement;null==
f&&(f=d.fontSizeIncrement);e.Ic.fontSizeIncrement=f;f=b.fontStyleOverride?a.C:a.B;e=b.fontStyle;null==e&&(e=d.bold&&d.bi?3:d.bold?1:d.bi?2:0);f=f.Ic;switch(e){case 1:f.bold=!0;delete f.bi;break;case 2:delete f.bold;f.bi=!0;break;case 3:f.bold=!0;f.bi=!0;break;default:delete f.bold,delete f.bi}e=b.textOpacityOverride?a.C:a.B;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Ic.textOpacity=f;e=b.windowOpacityOverride?a.C:a.B;f=b.windowOpacity;null==f&&(f=V2.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.C:a.B;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Ic.charEdgeStyle=f;e=b.fontFamilyOverride?a.C:a.B;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Ic.fontFamily=f;a.loaded&&a.IA();c&&T2(a,"display-settings",b)},PGa=function(a,b){if(b&&!a.L){var c=jGa({Ve:0,
lang:"en"});a.L=[c,new f2(c.start,c.end-c.start,0,c.id,"Captions look like this")];a.player.ud(a.L)}else!b&&a.L&&(OGa(a,a.L),a.L=null)},OGa=function(a,b){a.player.Mf(b);
g.Ab(b,function(c){g.kb(this.Y,c)},a);
R1(a.ca)},M2=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},T2=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}};
g.vN.prototype.rq=g.ca(23,function(){this.aa();for(var a=g.se(document,"track",void 0,this.i),b=0;b<a.length;b++)g.Me(a[b])});
g.fS.prototype.rq=g.ca(22,function(){this.i.rq()});
g.vN.prototype.rs=g.ca(21,function(){return!(!this.i.textTracks||!this.i.textTracks.addEventListener)});
g.fS.prototype.rs=g.ca(20,function(){return this.i.rs()});
g.vN.prototype.qs=g.ca(19,function(){return!!this.i.textTracks});
g.fS.prototype.qs=g.ca(18,function(){return this.i.qs()});
g.vN.prototype.hq=g.ca(17,function(a){this.aa();for(var b=0;b<a.length;b++)this.i.appendChild(a[b])});
g.fS.prototype.hq=g.ca(16,function(a){this.i.hq(a)});
g.Ey.prototype.Rt=g.ca(1,function(){return 0});
g.fz.prototype.Rt=g.ca(0,function(a){return(a=this.Th(a))?a.l:0});
var IGa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;g.u(W1,g.E);g.k=W1.prototype;g.k.mu=function(){};
g.k.nu=function(){};
g.k.Ak=function(){};
g.k.Eo=function(){return""};
g.k.oG=function(){return!1};
g.k.da=function(){this.Ak();g.E.prototype.da.call(this)};
g.u(X1,W1);X1.prototype.mu=function(a,b,c){var d=this;this.na();b=this.Eo(a,b);this.Ak();this.i=g.Pp(b,{format:"RAW",onSuccess:function(e){d.i=null;c(e.responseText,a)},
withCredentials:!0})};
X1.prototype.nu=function(a){if(this.audioTrack)for(var b=g.q(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())V1(this.l,c.value);a()};
X1.prototype.Eo=function(a,b){var c=a.url,d={fmt:b};if("srv3"===b||"3"===b||"json3"===b)g.Yp()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3});a.translationLanguage&&(d.tlang=T1(a));return g.zp(c,d)};
X1.prototype.Ak=function(){this.i&&this.i.abort()};
Y1.prototype.contains=function(a){a=g.vb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
Y1.prototype.length=function(){return this.segments.length/2};
g.u(Z1,g.E);g.k=Z1.prototype;g.k.da=function(){g.E.prototype.da.call(this);this.l&&this.l.cancel()};
g.k.qB=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.pc();var b=this.i;this.i=g.ab(this.X.ql(a).i);b!==this.i&&this.L&&this.L()};
g.k.reset=function(){this.B=new Y1;this.l&&(this.l.cancel(),this.l=null)};
g.k.DE=function(){this.na();var a;if(a=null!=this.i)a=this.i,a=a.i.Ik(a);!a||this.l||this.i&&30<this.i.startTime-this.player.getCurrentTime()||(a=this.i,a=a.i.Rp(a),a.i[0].duration?(this.B.contains(a.i[0].va)||VFa(this,a),this.i=g.ab(a.i)):!g.U(this.W.experiments,"force_caption_seek_for_live_killswitch")&&this.i&&this.i.B&&this.i.B+this.player.pc()<this.player.getCurrentTime()&&this.seekTo(this.player.getCurrentTime()));this.J.start()};
g.u($1,W1);g.k=$1.prototype;g.k.mu=function(a,b,c){var d=this;this.Ak();b=XFa(this,a.getId());b||(b=a.languageCode,b=this.i.isManifestless?YFa(this,b,"386"):YFa(this,b));if(b){var e=1E3*(b.index.Rt(b.index.Vh())-b.index.mf(b.index.Vh()));this.u=new Z1(new g.ex,this.G,b,function(f,h){c(f,a,h,e)},this.I||g.Ww(b.info),function(){d.u&&d.u.reset();
d.B=!0})}};
g.k.oG=function(){var a=this.B;this.B=!1;return a};
g.k.nu=function(a){var b=this.I?[new g.QG({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.QG({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.i.isManifestless?WFa(this,"386"):WFa(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())V1(this.l,c.value);a()};
g.k.Ak=function(){this.u&&(this.u.dispose(),this.u=null)};
g.k.Eo=function(){return""};
g.u(a2,W1);a2.prototype.mu=function(a,b,c){var d=this;this.na();b=this.Eo(a,b);this.Ak();this.i=g.Pp(b,{format:"RAW",onSuccess:function(e){d.i=null;c(e.responseText,a)},
withCredentials:!0})};
a2.prototype.nu=function(a){var b=this,c=this.u,d={type:"list",tlangs:1,v:this.videoId,vssids:1};this.cE&&(d.asrs=1);c=g.zp(c,d);this.Ak();this.i=g.Pp(c,{format:"RAW",onSuccess:function(e){b.i=null;if((e=e.responseXML)&&e.firstChild){for(var f=e.getElementsByTagName("track"),h=0;h<f.length;h++){var l=f[h],m=l.getAttribute("lang_code"),n=l.getAttribute("lang_translated"),p=l.getAttribute("name"),r=l.getAttribute("kind"),t=l.getAttribute("id"),w="true"===l.getAttribute("lang_default"),x="true"===l.getAttribute("cantran");
l=l.getAttribute("vss_id");V1(b.l,new g.QG({languageCode:m,languageName:n,name:p,kind:r,id:t,is_servable:!0,is_translateable:x,vss_id:l,is_default:w}))}e=e.getElementsByTagName("target");f=e.length;for(h=0;h<f;h++)m={languageCode:e[h].getAttribute("lang_code"),languageName:e[h].getAttribute("lang_translated"),languageOriginal:e[h].getAttribute("lang_original"),id:e[h].getAttribute("id"),isDefault:"true"===e[h].getAttribute("lang_default")},b.B[m.languageCode]=m.languageName,b.C.push(m)}a()},
withCredentials:!0})};
a2.prototype.Eo=function(a,b){var c=this.u,d={v:this.videoId,type:"track",lang:a.languageCode,name:a.getName(),kind:a.kind,fmt:b};a.translationLanguage&&(d.tlang=T1(a));return c=g.zp(c,d)};
a2.prototype.Ak=function(){this.i&&this.i.abort()};
var n2=/^#(?:[0-9a-f]{3}){1,2}$/i,$Fa=/#(.)(.)(.)/,ZFa=/^#(?:[0-9a-f]{3}){1,2}$/i;var bGa=["left","right","center","justify"];g.u(c2,g.X);g.k=c2.prototype;g.k.sJ=function(a,b){var c=g.vg(this.element,this.element.parentElement);this.Ha=a-c.x;this.La=b-c.y;g.N(this.element,"ytp-dragging")};
g.k.rJ=function(a,b){var c=g.xg(this.element),d=a-this.Ha-.02*this.playerWidth,e=b-this.La-.02*this.playerHeight,f=(d+c.width/2)/this.maxWidth*3;f=Math.floor(g.ee(f,0,2));var h=(e+c.height/2)/this.za*3;h=Math.floor(g.ee(h,0,2));var l=f+3*h;d=(d+f/2*c.width)/this.maxWidth;d=100*g.ee(d,0,1);c=(e+h/2*c.height)/this.za;c=100*g.ee(c,0,1);this.l.params.Oh=l;this.l.params.Ci=c;this.l.params.Pg=d;this.i.Oh=l;this.i.Ci=c;this.i.Pg=d;this.KG()};
g.k.qJ=function(){g.gn(this.element,"ytp-dragging")};
g.k.KG=function(){this.tp(this.C)};
g.k.Eb=function(){return this.type};
g.k.tp=function(a){var b=Math.min(this.DD(),this.maxWidth),c=this.CD(),d="";3===this.l.params.Ve&&(d="rotate(180deg)");g.hg(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Xw(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.i.Pg+2;d=this.i.Oh;switch(d){case 0:case 3:case 6:(b=this.i.Ic.fontSizeIncrement)&&0<b&&2!==this.i.Ve&&3!==
this.i.Ve&&(e=Math.max(e/(1+2*b),2));a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.B.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.i.Ci+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.hg(this.element,
a)};
g.k.Xw=function(a){var b;for(b=0;b<a.length&&a[b]===this.C[b];b++);if(this.ca||this.C.length>b)b=0,this.ca=!1,this.C=[],this.I=this.ia=this.ea=null,g.Ke(this.B);for(;b<a.length;b++)fGa(this,a[b])};
g.k.DD=function(){return 0};
g.k.CD=function(){return 0};
g.k.toString=function(){return g.X.prototype.toString.call(this)};g.u(d2,c2);d2.prototype.Xw=function(a){var b=this.l.i;c2.prototype.Xw.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.i===e)var d=f;else{d={};g.Sa(d,c.i);g.Sa(d,QGa);var e=c.i;var f=d}fGa(this,c,d)}};
var QGa={OL:!0};g.u(e2,c2);g.k=e2.prototype;g.k.KG=function(){this.ma.ng()};
g.k.NO=function(){g.gn(this.element,"ytp-rollup-mode");this.tp(this.Ya,!0)};
g.k.CD=function(){return this.u?this.X:this.L};
g.k.DD=function(){return this.u?this.L:this.X};
g.k.tp=function(a,b){this.Ya=a;if(this.l.params.tk){for(var c=0,d=0;d<this.C.length&&c<a.length;d++)this.C[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.C.concat(a.slice(c)));this.Oa=this.X;this.L=this.X=0;c2.prototype.tp.call(this,a);iGa(this,b)}c2.prototype.tp.call(this,a)};g.u(f2,g.yD);f2.prototype.toString=function(){return g.yD.prototype.toString.call(this)};g.u(g2,g.yD);g2.prototype.toString=function(){return g.yD.prototype.toString.call(this)};
var h2=0;g.u(i2,g.E);i2.prototype.l=function(){return[]};
i2.prototype.reset=function(){};g.u(j2,i2);j2.prototype.reset=function(){this.L={};this.u=this.i=null;this.J=!0};
j2.prototype.l=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.q(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.q(e),c=e.next();!c.done;c=e.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var h=this.B,l={},m=c.getAttribute("p");m&&g.Sa(l,this.B[m]);m=l2(c,"b");null!=m&&
(l.bold=m);m=l2(c,"i");null!=m&&(l.bi=m);m=l2(c,"u");null!=m&&(l.underline=m);m=m2(c,"et");null!=m&&(l.charEdgeStyle=m);m=m2(c,"of");null!=m&&(l.offset=m);m=o2(c,"bc");null!=m&&(l.background=m);m=o2(c,"ec");null!=m&&(l.kx=m);m=o2(c,"fc");null!=m&&(l.color=m);m=m2(c,"fs");null!=m&&0!==m&&(l.fontFamily=m);m=k2(c,"sz");void 0!==m&&(l.fontSizeIncrement=m/100-1);m=k2(c,"bo");void 0!==m&&(l.backgroundOpacity=m/255);m=k2(c,"fo");void 0!==m&&(l.textOpacity=m/255);m=m2(c,"rb");null!=m&&10!==m&&0!==m&&(l.Cd=
10<m?m-1:m);c=m2(c,"hg");null!=c&&(l.YD=c);h[d]=l;break;case "ws":d=c.getAttribute("id");this.X[d]=mGa(this,c);break;case "wp":d=c.getAttribute("id"),this.W[d]=nGa(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.q(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "w":this.i=oGa(this,d,e,!1);(d=this.L[this.i.id])&&d.end>this.i.start&&(d.end=this.i.start);this.L[this.i.id]=this.i;c.push(this.i);break;case "p":var n=e;h=[];l=d.getAttribute("w")||this.I;m=!!l2(d,
"a");n=(k2(d,"t")||0)+n;var p=k2(d,"d")||5E3;m||(!this.J&&this.u&&this.u.windowId===l&&this.u.end>n&&(this.u.end=n),this.u&&"\n"===this.u.text&&(this.u.text=""));var r=m?6:5,t=d.getAttribute("p");t=t?this.B[t]:null;var w=Array.from(d.childNodes);w.length&&(this.J=null!=d.getAttribute("d"));for(var x=0;x<w.length;x++){var y=w[x],F=void 0;0<x&&(m=!0);var B=void 0;1===y.nodeType&&(B=y);if(B&&"s"===B.tagName){if((y=(y=B.getAttribute("p"))?this.B[y]:null)&&y.Cd&&(1===y.Cd?(y=w.slice(x,x+4),4===y.length&&
(F=lGa(n,p,l,m,r,y,this.B),x+=3)):F=lGa(n,p,l,m,r,[B],this.B)),!F){var G=B;F=n;B=p;y=l;var K=m,M=r,H=G.textContent?G.textContent:"",L=G.getAttribute("p");L=L?this.B[L]:null;G=k2(G,"t")||0;F=new f2(F+G,B-G,M,y,H,K,L)}}else F=new f2(n,p,r,l,y.textContent||"",m,t);h.push(F);this.u=F}if(0<h.length)for(h[0].windowId===this.I&&(this.i=oGa(this,d,e,!0),c.push(this.i)),d=g.q(h),h=d.next();!h.done;h=d.next())h=h.value,h.windowId=this.i.id,this.i.i.push(h),c.push(h)}e=c}else e=[];return e};var RGa=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.u(p2,i2);p2.prototype.reset=function(){this.u.clear()};
p2.prototype.l=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens)for(var d=0,e=g.q(c.pens),f=e.next();!f.done;f=e.next()){f=f.value;var h={},l=f.pParentId;l&&Object.assign(h,this.i.get(l));f.bAttr&&(h.bold=!0);f.iAttr&&(h.bi=!0);f.uAttr&&(h.underline=!0);l=f.ofOffset;null!=l&&(h.offset=l);void 0!==f.szPenSize&&(h.fontSizeIncrement=f.szPenSize/100-1);l=f.etEdgeType;null!=l&&(h.charEdgeStyle=l);void 0!==f.ecEdgeColor&&(h.kx=q2(f.ecEdgeColor));l=f.fsFontStyle;null!=l&&0!==l&&(h.fontFamily=l);
void 0!==f.fcForeColor&&(h.color=q2(f.fcForeColor));void 0!==f.foForeAlpha&&(h.textOpacity=f.foForeAlpha/255);void 0!==f.bcBackColor&&(h.background=q2(f.bcBackColor));void 0!==f.boBackAlpha&&(h.backgroundOpacity=f.boBackAlpha/255);(l=f.rbRuby)&&10!==l&&(h.Cd=10<l?l-1:l,h.Ai=RGa.get(h.Cd));f.hgHorizGroup&&(h.YD=f.hgHorizGroup);this.i.set(d++,h)}if(c.wsWinStyles)for(d=0,e=g.q(c.wsWinStyles),f=e.next();!f.done;f=e.next())f=f.value,h={},(l=f.wsParentId)?Object.assign(h,this.C.get(l)):Object.assign(h,
this.I),void 0!==f.mhModeHint&&(h.Wo=f.mhModeHint),void 0!==f.juJustifCode&&(h.textAlign=f.juJustifCode),void 0!==f.pdPrintDir&&(h.Ve=f.pdPrintDir),void 0!==f.sdScrollDir&&(h.pA=f.sdScrollDir),void 0!==f.wfcWinFillColor&&(h.windowColor=q2(f.wfcWinFillColor)),void 0!==f.wfoWinFillAlpha&&(h.windowOpacity=f.wfoWinFillAlpha/255),this.C.set(d++,h);if(c.wpWinPositions)for(d=0,e=g.q(c.wpWinPositions),f=e.next();!f.done;f=e.next())f=f.value,h={},(l=f.wpParentId)&&Object.assign(h,this.B.get(l)),void 0!==f.ahHorPos&&
(h.Pg=f.ahHorPos),void 0!==f.apPoint&&(h.Oh=f.apPoint),void 0!==f.avVerPos&&(h.Ci=f.avVerPos),void 0!==f.ccCols&&(h.Uk=f.ccCols),void 0!==f.rcRows&&(h.tk=f.rcRows),this.B.set(d++,h);if(c.events)for(d=[],c=g.q(c.events),e=c.next();!e.done;e=c.next()){var m=e.value;e=(m.tStartMs||0)+b;f=m.dDurationMs||0;if(m.id)h=String(m.id),e=pGa(this,m,e,f,h),d.push(e),this.u.set(h,e);else{m.wWinId?h=m.wWinId.toString():(h="_"+h2++,l=pGa(this,m,e,f,h),d.push(l),this.u.set(h,l));0===f&&(f=5E3);l=this.u.get(h);var n=
!!m.aAppend,p=n?6:5,r=m.segs,t=null;m.pPenId&&(t=this.i.get(m.pPenId));for(m=0;m<r.length;m++){var w=r[m],x=w.utf8;if(x){var y=w.tOffsetMs||0,F=null;w.pPenId&&(F=this.i.get(w.pPenId));if(2===(null!=l.params.Wo?l.params.Wo:1<l.i.length?1:0)&&n&&"\n"===x)continue;if(w=F&&1===F.Cd)if(w=m,w+3>=r.length||!r[w+1].pPenId||!r[w+2].pPenId||!r[w+3].pPenId)w=!1;else{var B=r[w+1].pPenId;(B=this.i.get(B))&&B.Cd&&2===B.Cd?(B=r[w+2].pPenId,B=this.i.get(B),!B||!B.Cd||3>B.Cd?w=!1:(B=r[w+3].pPenId,w=(B=this.i.get(B))&&
B.Cd&&2===B.Cd?!0:!1)):w=!1}if(w){y=r[m+1].utf8;w=r[m+3].utf8;B=r[m+2].utf8;var G=this.i.get(r[m+2].pPenId);x=kGa(x,y,B,w,G);n=new f2(e,f,p,h,x,n,F);m+=3}else n=new f2(e+y,f-y,p,l.id,x,n,F||t);n&&(d.push(n),l.i.push(n))}n=!0}}}else d=[];return d};s2.prototype.clear=function(){this.u=this.time=this.mode=0;this.i=[];this.reset()};
s2.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var qGa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];t2.prototype.set=function(a){this.type=a};
t2.prototype.get=function(){return this.type};
u2.prototype.clear=function(){this.state=0};
u2.prototype.update=function(){this.state=2===this.state?1:0};
u2.prototype.isValid=function(){return 0!==this.state};
u2.prototype.matches=function(a,b){return this.isValid()&&a===this.Im&&b===this.Qk};
vGa.prototype.reset=function(){this.timestamp=this.i=0};
v2.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.u[b][c].timestamp=a};
v2.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.u[b][c];a=0===d.i?a+"_":a+String.fromCharCode(d.i)}a+="\n"}return a};
v2.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.u[b][c].reset();this.B=a;this.i=0;this.l=this.row=1};
var wGa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],xGa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],yGa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],zGa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];B2.prototype.reset=function(a,b){this.C=b;this.style.set(2);this.l=this.I;this.B=this.J;this.i=this.l;var c=(a<<2)+(b<<1);this.I.reset(c);this.J.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
r2.prototype.reset=function(a){this.C=a;this.l.clear();this.B=this.u;this.u.reset(a,0);this.I.reset(a,1)};EGa.prototype.B=function(){};g.u(D2,EGa);D2.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+h2++;c=c/1E3-this.I;d=d/1E3-this.I;a=new g2(c,d-c,5,f,{textAlign:0,Oh:0,Pg:2.5*b,Ci:5.33*a});e=new f2(c,d-c,5,f,e);this.l.push(a);this.l.push(e)}};
g.u(G2,i2);G2.prototype.l=function(a){a=new D2(a,a.byteLength,this.u);if(FGa(a)){for(;a.byteOffset<a.i.byteLength;)for(0===a.version?a.u=F2(a)*(1E3/45):1===a.version&&(a.u=4294967296*F2(a)+F2(a)),a.C=E2(a);0<a.C;a.C--){var b=E2(a),c=E2(a),d=E2(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.i,b.i.push({time:a.u,type:this.track,GC:c,HC:d,order:b.i.length}))}uGa(this.i,a);return a.l}return[]};
G2.prototype.reset=function(){this.i.clear()};g.u(I2,i2);
I2.prototype.l=function(a,b){for(var c=[],d=a.split(SGa),e=1;e<d.length;e++){var f=d[e],h=b;if(""!==f&&!TGa.test(f)){var l=W2.exec(f);if(l&&4<=l.length){var m=J2(l[1]),n=J2(l[2])-m;m+=h;var p=(l=l[3])?l.split(" "):[];l={};var r=null,t="",w=null,x="";l.textAlign=2;p=g.q(p);for(var y=p.next();!y.done;y=p.next())if(y=y.value.split(":"),2===y.length){var F=y[1];switch(y[0]){case "line":y=F.split(",");y[0].endsWith("%")&&(r=y[0],l.Ci=Number.parseInt(r,10),2===y.length&&(t=y[1].trim()));break;case "position":y=
F.split(",");w=y[0];l.Pg=Number.parseInt(w,10);2===y.length&&(x=y[1].trim());break;case "align":switch(F){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}r||(l.Ci=100,t||(t="end"));if(!w)switch(l.textAlign){case 0:l.Pg=0;break;case 1:l.Pg=100;break;default:l.Pg=50}r=0;switch(t){case "center":r+=3;break;case "end":r+=6;break;default:r+=0}switch(x){case "line-left":r+=0;break;case "center":r+=1;break;case "line-right":r+=2;break;default:switch(l.textAlign){case 0:r+=
0;break;case 2:r+=1;break;case 1:r+=2}}l.Oh=0>r||8<r?7:r;f=f.substring(W2.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");x=l;l=f;f={};if(0>l.indexOf("<")&&0>l.indexOf("&"))h=HGa(m,n,5,x),n=new f2(m,n,5,h.id,l,!1,g.Pb(f)?void 0:f),c.push(h),c.push(n),h.i.push(n);else for(t=l.split(UGa),1===t.length?(l=5,x=HGa(m,n,l,x)):(r=l=6,x=Object.assign({Uk:32},x),x=new g2(m,n,r,"_"+h2++,x)),c.push(x),r=m,w=0;w<t.length;w++)p=t[w],0===w%2?(y=g.D_("<html>"+p+"</html>"),y.getElementsByTagName("parsererror").length?
(F=y.createElement("span"),F.appendChild(y.createTextNode(p))):F=y.firstChild,GGa(this,r,n-(r-m),l,x,0<w,F,f,c)):r=J2(p)+h}W2.lastIndex=0}}return c};
var TGa=/^NOTE/,SGa=/(?:\r\n|\r|\n){2,}/,W2=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),UGa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.hS.gu(I2,{l:"wvppt"});g.u(K2,g.E);K2.prototype.clear=function(){this.i&&this.i.dispose();this.i=null};
K2.prototype.reset=function(){this.i&&this.i.reset()};
K2.prototype.da=function(){g.E.prototype.da.call(this);this.clear()};var V2={windowColor:"#080808",windowOpacity:0,textAlign:2,Oh:7,Pg:50,Ci:100,Ic:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.u(N2,g.hN);g.k=N2.prototype;g.k.da=function(){if(this.I||this.ea){var a=this.G.dd();a&&!a.na()&&a.rq()}else PGa(this,!1);g.hN.prototype.da.call(this)};
g.k.Gn=function(){if(this.Ha)return this.I||this.ea;var a=this.player.getAudioTrack().captionsInitialState;return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?P2(this):O2(this)||P2(this)?!0:KGa(this)};
g.k.load=function(){var a=this;g.hN.prototype.load.call(this);var b=!g.U(this.i.experiments,"web_player_captions_track_list_changed_killswitch");this.J=this.player.getAudioTrack();if(this.u)this.l&&(this.za.clear(),this.I?LGa(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.mu(this.l,"json3",function(d,e,f,h){if(d){a.u.oG()&&(a.Y=[],a.G.Re("captions"),R1(a.ca),a.za.reset());var l=a.za;f=f||0;h=h||0;if(l.l.Z("html5_disable_rawcc_killswitch")){if("string"!==typeof d){var m=new DataView(d);
8<=m.byteLength&&1718909296===m.getUint32(4)&&(m=g.Qv(m,0,1835295092),d=d.slice(m.dataOffset,m.dataOffset+m.size),H2(d)||(d=g.Ye(new Uint8Array(d))))}}else"string"===typeof d||H2(d)||(m=new DataView(d),d=8>=m.byteLength||1718909296!==m.getUint32(4)?"":(m=g.Qv(m,0,1835295092))&&m.size?g.Ye(new Uint8Array(d.slice(m.dataOffset,m.dataOffset+m.size))):"");if(d)try{if("string"!==typeof d){var n=d,p=f,r=h;if(!H2(n))throw Error("Invalid binary caption track data");l.i||(l.i=new G2(r,e));var t=l.i.l(n,p)}else{if("WEBVTT"===
d.substring(0,6))e=d,r=f,l.i||(l.i=new I2),p=l.i.l(e,r),.01>Math.random()&&g.kt(Error("Deprecated subtitles format in web player: WebVTT")),n=p;else b:{p=d;if("{"===p[0])try{l.i||(l.i=new p2(JGa(e)));n=l.i.l(p,f);break b}catch(G){g.jt(G);n=[];break b}r=g.D_(p);if(!r||!r.firstChild){var w=Error("Invalid caption track data");w.params=p;throw w;}if("timedtext"===r.firstChild.tagName){if(3===Number(r.firstChild.getAttribute("format"))){l.i||(l.i=new j2(JGa(e),l.l));n=l.i.l(r,f);break b}var x=Error("Unsupported subtitles format in web player (Format2)");
x.params=p;throw x;}if("transcript"===r.firstChild.tagName){var y=Error("Unsupported subtitles format in web player (Format1)");y.params=p;throw y;}var F=Error("Invalid caption track data");F.params=p;throw F;}t=n}var B=t}catch(G){g.jt(G),l.clear(),B=[]}else B=[];a.player.ud(B);!a.X||a.ea||S2(a)||g.hG(a.i)||g.ZF(a.i)||(g.an(a.ga),B=jGa({Oh:0,Pg:5,Ci:5,tk:2,textAlign:0,Ve:0,lang:"en"}),a.la=[B],l=["Click "," for settings"],a.Ja||(t=new g.XK(g.mL()),g.I(a,t),a.Ja=t.element),t=B.end-B.start,(e=g.RG(a.l))&&
a.la.push(new f2(B.start,t,0,B.id,e)),a.la.push(new f2(B.start,t,0,B.id,l[0]),new f2(B.start,t,0,B.id,a.Ja,!0),new f2(B.start,t,0,B.id,l[1],!0)),a.player.ud(a.la),g.$m(a.ga));!a.X||a.ea||S2(a)||(g.yG(a.i)?(0,g.$_)(!0):T2(a,"module-enabled",!0),a.J&&(a.J.C=a.l),a.player.Nn());a.X=!1}}),!b||this.I||this.ea||S2(this)||this.player.xa("captionschanged",S1(this.l))),b||(this.l&&!S2(this)?this.player.xa("captionschanged",S1(this.l)):this.player.xa("onCaptionsTrackListChanged"));
else{var c;this.La?c=new $1(this.videoData.i,this.player):this.Ya?c=new X1(this.i,this.videoData,this.player.getAudioTrack()):c=new a2(this.videoData.fh,this.videoData.videoId,this.videoData.captionsLanguagePreference||this.i.captionsLanguagePreference||g.cI(this.videoData,"yt:cc_default_lang")||this.i.md,this.videoData.Rv,this.i);this.u=c;g.I(this,this.u);c.nu(function(){var d=a.player.getAudioTrack().captionsInitialState,e;"CAPTIONS_INITIAL_STATE_UNKNOWN"===d?O2(a)||a.X||KGa(a)?e=R2(a,a.X):P2(a)&&
(e=Q2(a)):"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===d?e=R2(a,a.X):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===d&&P2(a)&&(e=Q2(a));if(a.I||a.ea){var f=U1(a.u.l,!0);d=[];for(var h=0;h<f.length;h++){var l=f[h],m=g.Ie("TRACK");m.setAttribute("kind","subtitles");m.setAttribute("label",g.RG(l));m.setAttribute("srclang",T1(l));m.setAttribute("id",l.toString());a.ea||m.setAttribute("src",a.u.Eo(l,"vtt"));l===e&&m.setAttribute("default","1");d.push(m)}e=a.G.dd();e.hq(d);e=e.he();a.Oa&&a.ia.N(e.textTracks,"change",
a.rP)}else!a.l&&e&&U2(a,e),a.player.xa("onCaptionsTrackListChanged"),a.player.xa("onApiChange")})}};
g.k.unload=function(){this.I&&this.l?LGa(this,!1):(this.ga&&g.an(this.ga),this.player.Re("captions"),this.Y=[],this.u&&this.u.Ak(),this.za.clear(),this.L&&this.player.ud(this.L),this.IA());g.hN.prototype.unload.call(this);this.player.Nn();this.player.xa("captionschanged",{})};
g.k.create=function(){this.Gn()&&this.load()};
g.k.rP=function(){for(var a=this.G.dd().he().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;var d=U1(this.u.l,!0);for(var e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.l:null)!==b&&U2(this,b,!0)};
g.k.VQ=function(){!this.l&&this.I||this.unload()};
g.k.Bd=function(a){this.Y.push(a);R1(this.ca)};
g.k.rf=function(a){g.kb(this.Y,a);this.u instanceof $1&&this.u.I&&this.player.Mf([a]);R1(this.ca)};
g.k.WP=function(a){if(a instanceof g2){var b=this.W[a.id];b&&b.l!==a&&(b.dispose(),delete this.W[a.id],b=null);b||(b=NGa(this,a))&&(this.W[a.id]=b)}else b=a.windowId,this.ma[b]||(this.ma[b]=[]),this.ma[b].push(a)};
g.k.getCaptionWindowContainerId=function(){return this.Da.element.id};
g.k.dQ=function(){OGa(this,this.la);this.la=null};
g.k.GA=function(){var a=this;this.ca.stop();g.Qb(this.ma);this.Y.sort(g.AD);var b=this.Y;if(this.L){var c=g.Ne(b,function(d){return-1===this.L.indexOf(d)},this);
c.length&&(b=c)}g.Ab(b,this.WP,this);g.Cb(this.W,function(d,e){a.ma[e]?(d.element.parentNode||(d instanceof e2||d instanceof d2||g.Fb(a.W,function(f,h){h!==e&&f.l.params.Oh===d.l.params.Oh&&f.l.params.Pg===d.l.params.Pg&&f.l.params.Ci===d.l.params.Ci&&(f.dispose(),delete a.W[h]);return h===e},a),MGa(a,d.element)),d.tp(a.ma[e])):(d.dispose(),delete a.W[e])},this)};
g.k.hQ=function(){L2(this,{},!0);g.U(this.i.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.xa("captionssettingschanged")};
g.k.oL=function(){var a=V2.Ic;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.bi?3:a.bold?1:a.bi?2:0,textOpacity:a.textOpacity,windowColor:V2.windowColor,windowOpacity:V2.windowOpacity};var b=M2(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.BH=function(a,b){var c={};g.Sa(c,M2(this,"display-settings"));g.Sa(c,a);L2(this,c,b);this.player.xa("captionssettingschanged")};
g.k.IA=function(){!this.I&&this.loaded&&(g.Cb(this.W,function(a,b){a.dispose();delete this.W[b]},this),this.GA())};
g.k.He=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.ee(b,-2,4);this.BH({fontSizeIncrement:c});return c;case "reload":b&&!this.I&&U2(this,this.l,!0);break;case "stickyLoading":void 0!==b&&this.i.u&&(g.yG(this.i)?(0,g.$_)(!!b):T2(this,"module-enabled",!!b));break;case "track":if(!this.u)return{};if(b){if(this.I)break;if(!g.Oa(b))break;if(g.Pb(b)){U2(this,null,!0);break}for(var d=U1(this.u.l,!0),e=0;e<d.length;e++){var f=d[e];f.languageCode!==b.languageCode||c&&f.languageName!==
b.languageName||(c=b.translationLanguage?RFa(f,b.translationLanguage):f)}!c||c===this.l&&this.loaded||(d=(0,g.Ina)(),e=T1(c),d.length&&e===d[d.length-1]||(d.push(e),(0,g.ODa)(d)),U2(this,c,!0))}else return this.loaded&&this.l&&!S2(this)?S1(this.l):{};return"";case "tracklist":return this.u?g.Qc(U1(this.u.l,!(!b||!b.includeAsr)),function(h){return S1(h)}):[];
case "translationLanguages":return this.u?this.u.C.map(function(h){return Object.assign({},h)}):[];
case "sampleSubtitles":this.I||void 0===b||PGa(this,!!b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.i.u&&a.push("stickyLoading");return a};
g.k.ny=function(){var a=this.l;return a?{cc:a.vssId}:{}};
g.k.JQ=function(){this.loaded&&this.l&&!S2(this)?(g.yG(this.i)?(0,g.$_)(!1):T2(this,"module-enabled",!1),this.unload(),P2(this,!0)&&U2(this,Q2(this),!1)):U2(this,S2(this)||!this.l?R2(this,!0):this.l,!0)};
g.k.WM=function(){var a=S2(this);P2(this,a)?U2(this,this.player.getAudioTrack().l,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.Gn()&&(a?U2(this,R2(this),!1):this.load()))};
g.hS.gu(N2,{GA:"smucd"});g.nN.captions=N2;})(_yt_player);
